### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#2]
The current output of errors in jobs is not great. Errors only show up with something like the following:

```
15:54:08.438 [error] Ranch listener Kitto.Router.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.288.0> exit with reason: {{:noproc, {GenServer, :call, [nil, {:get, #Function<1.3152883/1 in Kitto.Notifier.cache/0>}, 5000]}}, {Kitto.Router, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.288.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["events"], peer: {{127, 0, 0, 1}, 59233}, port: 4000, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4000"}, {"connection", "keep-alive"}, {"accept", "text/event-stream"}, {"cache-control", "no-cache"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"}, {"referer", "http://localhost:4000/dashboards/general"}, {"accept-encoding", "gzip, deflate, lzma, sdch, br"}, {"accept-language", "en-US,en;q=0.8"}, {"cookie", "_ga=GA1.1.1869598866.1476971830"}], request_path: "/events", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}
```

Which is useless for finding out what the actual error is.

**Comment by zorbash** [comment]
Agreed, when an error occurs in a job the most useful debugging info is:
- File/Line where the job is defined
- Name of the job
- Stacktrace

Internal procedures (like the job result being cached by `Kitto.Notifier.cache`) are quite irrelevant to the user.

**Comment by zorbash** [comment]
As mentioned in e71c3f7 the error output changed from:

## Before

```
16:15:06.596 [error] Process #PID<0.1727.0> raised an exception
** (RuntimeError) Boom Shakalaka
    (kitto) lib/kitto/stats_server.ex:66: Kitto.StatsServer.measure_func/2
    (kitto) lib/kitto/job.ex:35: Kitto.Job.with_interval/1
```

## After

```
15:58:27.230 [error] Process #PID<0.1442.0> raised an exception
** (Kitto.Job.Error) Job :buzzwords failed to run.
Defined in: jobs/buzzwords.ex:3:
Error: ** (RuntimeError) Boom Shakalaka
Stacktrace:     jobs/buzzwords.ex:10: anonymous fn/0 in :elixir_compiler_29.__FILE__/1
(stdlib) timer.erl:166: :timer.tc/1
  (kitto) lib/kitto/stats_server.ex:73: Kitto.StatsServer.timed_call/1
  (kitto) lib/kitto/stats_server.ex:46: Kitto.StatsServer.measure_call/1
  (kitto) lib/kitto/job.ex:35: Kitto.Job.with_interval/1
```

The change is compatible with the way jobs are currently defined.
